// NOTE: Any changes to this file must be reflected in the corresponding SPECS.md or NOTES.md.

package config

import (
	"fmt"
	"gopkg.in/yaml.v3"
	"os"
	"path/filepath"
)

// Load reads a YAML configuration file from path and merges it over the defaults.
// It returns an error if the file does not exist or contains invalid YAML.
// Any fields absent from the file receive their default values.
func Load(path string) (*Config, error) {
	cfg := Default()

	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open config: %w", err)
	}
	defer f.Close() //nolint:errcheck

	dec := yaml.NewDecoder(f)
	if err := dec.Decode(cfg); err != nil {
		if err.Error() == "EOF" {
			// Empty file — return defaults.
			return cfg, nil
		}
		return nil, fmt.Errorf("parse config: %w", err)
	}

	// Re-apply defaults for any zero-value fields that were not in the file.
	applyDefaults(cfg)

	return cfg, nil
}

// Default returns a Config with all fields set to their default values.
// It resolves the home directory for path defaults; it never writes to the filesystem.
func Default() *Config {
	home, _ := os.UserHomeDir()
	lthDir := filepath.Join(home, ".lth")

	cfg := &Config{}
	cfg.DB.Path = filepath.Join(lthDir, "memory.db")
	cfg.Embedding.Provider = "huggingface"
	cfg.Embedding.AutoDocker = true
	cfg.Embedding.DockerPort = 8080
	cfg.Embedding.BaseURL = "http://localhost:8080"
	cfg.Embedding.TimeoutS = 30
	cfg.LLM.Provider = "anthropic"
	cfg.LLM.AuthMode = "api_key"
	cfg.LLM.BaseURL = "http://localhost:11434"
	cfg.LLM.Model = "claude-haiku-4-5-20251001"
	cfg.LLM.TimeoutS = 60
	cfg.Compaction.IntervalS = 3600
	cfg.Compaction.L5Threshold = 50
	cfg.Compaction.L5MaxAgeH = 24
	cfg.Compaction.L5ClusterThreshold = 0.75
	cfg.Compaction.L5MinClusterSize = 2
	cfg.Compaction.L5MaxClusterChars = 80_000
	cfg.Compaction.L4ClusterSize = 5
	cfg.Compaction.L3EpisodesMin = 10
	cfg.Compaction.L3ImportanceMin = 7.0
	cfg.Compaction.SeedMinL2 = 10
	cfg.Compaction.SeedMinL3 = 20
	cfg.Compaction.SeedSample = 100
	cfg.Compaction.ValenceCompactionMin = 0.15
	cfg.Search.DefaultTopK = 10
	cfg.Search.Alpha = 0.333
	cfg.Search.Beta = 0.333
	cfg.Search.Gamma = 0.333
	cfg.Issues.IntervalS = 3600
	cfg.Markdown.Layer = 3
	cfg.Markdown.IntervalS = 300
	cfg.Markdown.GitPull = true
	cfg.Markdown.GitPullIntervalS = 3600
	cfg.Markdown.GitHub.CacheDir = filepath.Join(lthDir, "repos-cache")
	cfg.Markdown.GitHub.CloneDepth = 1
	cfg.Watcher.Paths = []string{
		filepath.Join(home, ".claude", "projects"),
		filepath.Join(home, ".pi", "agent", "sessions"),
	}
	cfg.GWS.IntervalH = 3
	cfg.GWS.LookbackDays = 14
	cfg.GWS.OutputDir = filepath.Join(lthDir, "gws-imports")
	cfg.GWS.NamePatterns = []string{"Notes by Gemini", "Transcript"}
	cfg.PR.CacheDir = filepath.Join(lthDir, "pr-repos-cache")
	cfg.PR.IntervalS = DefaultPRIntervalS
	cfg.PR.Layer = DefaultPRLayer
	cfg.PR.LookbackDays = 0 // unbounded -- mine full history, gradually, across scans
	cfg.PR.MaxPerScan = DefaultPRMaxPerScan
	cfg.PR.SkipAuthors = []string{"renovate[bot]", "dependabot[bot]", "github-actions[bot]"}
	cfg.Backup.IntervalH = DefaultBackupIntervalH
	cfg.Backup.Keep = DefaultBackupKeep
	cfg.Watcher.StateFile = filepath.Join(lthDir, "watcher-state.json")
	cfg.Watcher.LogRetainDays = 3
	cfg.API.ListenAddr = "localhost:10010"

	return cfg
}

// ConfigPath returns the canonical path for the lth configuration file.
func ConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("get home dir: %w", err)
	}
	return filepath.Join(home, ".lth", "config.yaml"), nil

}

// InitDefault writes the default configuration to path with explanatory comments.
// It returns an error if the file already exists (use force to overwrite).
func InitDefault(path string, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("config file already exists at %s (use --force to overwrite)", path)
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	content := `# lth configuration
# Generated by lth config init

# db:
#   path: "~/.lth/memory.db"  # default

embedding:
  # HuggingFace TEI embedding server (auto-started via Docker on first use).
  # Model is fixed to nomic-embed-text-v1.5 (change EmbeddingModel constant to switch).
  provider: huggingface
  base_url: "http://localhost:8080"
  timeout_s: 30
  auto_docker: true
  docker_port: 8080

llm:
  # Anthropic Claude for compaction, importance scoring, and tag extraction.
  provider: anthropic
  model: "claude-haiku-4-5-20251001"
  timeout_s: 60
  # Authentication mode:
  #   api_key  (default) -- uses the api_key field below or ANTHROPIC_API_KEY env var
  #   oauth            -- uses claude.ai Pro/Max via 'lth auth login'
  auth_mode: api_key
  # api_key: ""  # or set ANTHROPIC_API_KEY env var
  # oauth_credentials_path: ""  # default: ~/.lth/anthropic-oauth.json

compaction:
  interval_s: 3600
  l5_threshold: 50
  l5_max_age_h: 24
  l5_cluster_threshold: 0.75
  l5_min_cluster_size: 2
  # Prompt-content character budget per L5 cluster sent to the LLM. Oversized
  # clusters are downsampled to evenly-spaced representatives. 0 disables the
  # cap (original unbounded behaviour). 80000 ~= 20k tokens.
  l5_max_cluster_chars: 80000
  l4_cluster_size: 5
  l3_episodes_min: 10
  l3_importance_min: 7.0
  seed_min_l2: 10
  seed_min_l3: 20
  seed_sample: 100
  valence_compaction_min: 0.15

search:
  default_top_k: 10
  alpha: 0.333
  beta: 0.333
  gamma: 0.333

# watcher:
#   paths:
#     - "~/.claude/projects"
#     - "~/.pi/agent/sessions"
#   log_retain_days: 3   # daemon.log rotates daily; this many archives kept

# markdown:
#   # Scan local directories for files and extract facts via LLM.
#   dirs: [~/source/some-local-repo]
#   layer: 3
#   interval_s: 300
#   git_pull: true
#   git_pull_interval_s: 3600
#
#   # Optional: GitHub repos auto-cloned and refreshed by lth into cache_dir.
#   # Auth is delegated to local git (SSH keys, credential helpers).
#   github:
#     cache_dir: ~/.lth/repos-cache
#     clone_depth: 1                          # shallow clones (0 = full history)
#     repos:
#       - repo: example-org/some-monorepo
#         include: ["**/tempo/**"]            # any path with a 'tempo' directory
#         exclude: ["**/vendor/**"]
#         file_types: [".md", ".yaml", ".jsonnet"]
#         # branch: main                      # optional; defaults to origin/HEAD

# gws:
#   # Google Workspace meeting-notes / transcripts watcher. Requires the gws
#   # CLI (npm: google-workspace-cli) to be installed and authenticated.
#   # lth never handles Google credentials directly.
#   enabled: false
#   interval_h: 3                       # poll cadence (default: 3)
#   lookback_days: 14                   # window of recent docs to consider
#   output_dir: ~/.lth/gws-imports      # written to; the markdown watcher includes
#                                        # this dir in its scan automatically when
#                                        # gws.enabled is true (no markdown.dirs edit needed)
#   name_patterns:                      # OR'd; Drive 'name contains' clauses
#     - "Notes by Gemini"
#     - "Transcript"
#   exclude_patterns: []                # optional NAND'd skip list

# pr:
#   # Mines merged PR history for configured repos and stores an LLM-written
#   # summary of each new PR, backdated to its merge time so old PRs decay in
#   # search like old memories instead of scoring as fresh.
#   cache_dir: ~/.lth/pr-repos-cache  # own directory -- deliberately not
#                                     # shared with markdown.github.cache_dir;
#                                     # see PRConfig.CacheDir for why
#   interval_s: 21600           # poll cadence; default 6h -- PR history changes slowly
#   layer: 5
#   lookback_days: 0            # 0 = unbounded (mine full history, gradually, across scans)
#   max_per_scan: 10            # cap new PRs resolved+attempted per scan, across all sources
#   skip_authors:                # bot logins excluded from summarization
#     - "renovate[bot]"
#     - "dependabot[bot]"
#     - "github-actions[bot]"
#   sources:
#     - repo: grafana/deployment_tools
#       dir: ksonnet/environments/tempo
#       # path: ~/source/deployment_tools  # optional: use an existing local
#       #   checkout as-is instead of having lth clone/manage it. Omit path
#       #   (as above) to have lth clone into pr.cache_dir -- always as a
#       #   full clone.

# backup:
#   # Daily VACUUM INTO snapshot of the database, gzipped, into dir. Disabled
#   # until dir is set -- point it at a different disk/mount than db.path,
#   # or the backup can't survive the disk failure it exists to protect
#   # against.
#   dir: ""             # e.g. /mnt/backup-drive/lth-snapshots
#   interval_h: 24
#   keep: 7              # most recent snapshots retained; older ones pruned

# sync:
#   server_url: ""
#   account: ""
#   org: ""
#   user: ""
`

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	return nil
}

// applyDefaults fills in any zero-value fields with their defaults.
// This handles partial TOML files where some sections are absent.
func applyDefaults(cfg *Config) {
	def := Default()

	if cfg.DB.Path == "" {
		cfg.DB.Path = def.DB.Path
	}
	applyEmbeddingDefaults(cfg, def)
	applyLLMDefaults(cfg, def)
	applyCompactionDefaults(cfg, def)
	applySearchDefaults(cfg, def)
	applyWatcherDefaults(cfg, def)
	applyGWSDefaults(cfg, def)
	applyIssuesDefaults(cfg, def)
	applyPRDefaults(cfg, def)
	applyBackupDefaults(cfg, def)
	applyMarkdownDefaults(cfg, def)
	applyAPIDefaults(cfg, def)
}

func applyWatcherDefaults(cfg, def *Config) {
	if len(cfg.Watcher.Paths) == 0 {
		cfg.Watcher.Paths = def.Watcher.Paths
	}
	if cfg.Watcher.StateFile == "" {
		cfg.Watcher.StateFile = def.Watcher.StateFile
	}
	if cfg.Watcher.LogRetainDays == 0 {
		cfg.Watcher.LogRetainDays = def.Watcher.LogRetainDays
	}
}

func applyGWSDefaults(cfg, def *Config) {
	if cfg.GWS.IntervalH == 0 {
		cfg.GWS.IntervalH = def.GWS.IntervalH
	}
	if cfg.GWS.LookbackDays == 0 {
		cfg.GWS.LookbackDays = def.GWS.LookbackDays
	}
	if cfg.GWS.OutputDir == "" {
		cfg.GWS.OutputDir = def.GWS.OutputDir
	}
	if len(cfg.GWS.NamePatterns) == 0 {
		cfg.GWS.NamePatterns = def.GWS.NamePatterns
	}
}

func applyIssuesDefaults(cfg, def *Config) {
	if cfg.Issues.IntervalS == 0 {
		cfg.Issues.IntervalS = def.Issues.IntervalS
	}
}

func applyPRDefaults(cfg, def *Config) {
	if cfg.PR.CacheDir == "" {
		cfg.PR.CacheDir = def.PR.CacheDir
	}
	if cfg.PR.IntervalS == 0 {
		cfg.PR.IntervalS = def.PR.IntervalS
	}
	if cfg.PR.Layer == 0 {
		cfg.PR.Layer = def.PR.Layer
	}
	if cfg.PR.LookbackDays == 0 {
		cfg.PR.LookbackDays = def.PR.LookbackDays
	}
	if cfg.PR.MaxPerScan == 0 {
		cfg.PR.MaxPerScan = def.PR.MaxPerScan
	}
	if len(cfg.PR.SkipAuthors) == 0 {
		cfg.PR.SkipAuthors = def.PR.SkipAuthors
	}
}

func applyBackupDefaults(cfg, def *Config) {
	if cfg.Backup.IntervalH == 0 {
		cfg.Backup.IntervalH = def.Backup.IntervalH
	}
	if cfg.Backup.Keep == 0 {
		cfg.Backup.Keep = def.Backup.Keep
	}
}

func applyMarkdownDefaults(cfg, def *Config) {
	if cfg.Markdown.Layer == 0 {
		cfg.Markdown.Layer = def.Markdown.Layer
	}
	if cfg.Markdown.IntervalS == 0 {
		cfg.Markdown.IntervalS = def.Markdown.IntervalS
	}
	if cfg.Markdown.GitPullIntervalS == 0 {
		cfg.Markdown.GitPullIntervalS = def.Markdown.GitPullIntervalS
	}
	if cfg.Markdown.GitHub.CacheDir == "" {
		cfg.Markdown.GitHub.CacheDir = def.Markdown.GitHub.CacheDir
	}
	if cfg.Markdown.GitHub.CloneDepth == 0 {
		cfg.Markdown.GitHub.CloneDepth = def.Markdown.GitHub.CloneDepth
	}
}

func applyAPIDefaults(cfg, def *Config) {
	if cfg.API.ListenAddr == "" {
		cfg.API.ListenAddr = def.API.ListenAddr
	}
}

func applyEmbeddingDefaults(cfg, def *Config) {
	if cfg.Embedding.Provider == "" {
		cfg.Embedding.Provider = def.Embedding.Provider
	}
	if cfg.Embedding.DockerPort == 0 {
		cfg.Embedding.DockerPort = def.Embedding.DockerPort
	}
	if cfg.Embedding.BaseURL == "" {
		if cfg.Embedding.Provider == "huggingface" {
			cfg.Embedding.BaseURL = "http://localhost:8080"
		} else {
			cfg.Embedding.BaseURL = "http://localhost:11434"
		}
	}
	if cfg.Embedding.TimeoutS == 0 {
		cfg.Embedding.TimeoutS = def.Embedding.TimeoutS
	}
}

func applyLLMDefaults(cfg, def *Config) {
	if cfg.LLM.Provider == "" {
		cfg.LLM.Provider = def.LLM.Provider
	}
	if cfg.LLM.AuthMode == "" {
		cfg.LLM.AuthMode = def.LLM.AuthMode
	}
	if cfg.LLM.Model == "" {
		switch cfg.LLM.Provider {
		case "anthropic":
			cfg.LLM.Model = "claude-haiku-4-5-20251001"
		default:
			cfg.LLM.Model = "llama3.2"
		}
	}
	if cfg.LLM.BaseURL == "" {
		cfg.LLM.BaseURL = def.LLM.BaseURL
	}
	if cfg.LLM.TimeoutS == 0 {
		cfg.LLM.TimeoutS = def.LLM.TimeoutS
	}
}

func applyCompactionDefaults(cfg, def *Config) {
	if cfg.Compaction.IntervalS == 0 {
		cfg.Compaction.IntervalS = def.Compaction.IntervalS
	}
	if cfg.Compaction.L5Threshold == 0 {
		cfg.Compaction.L5Threshold = def.Compaction.L5Threshold
	}
	if cfg.Compaction.L5MaxAgeH == 0 {
		cfg.Compaction.L5MaxAgeH = def.Compaction.L5MaxAgeH
	}
	if cfg.Compaction.L5ClusterThreshold == 0 {
		cfg.Compaction.L5ClusterThreshold = def.Compaction.L5ClusterThreshold
	}
	if cfg.Compaction.L5MinClusterSize == 0 {
		cfg.Compaction.L5MinClusterSize = def.Compaction.L5MinClusterSize
	}
	if cfg.Compaction.L5MaxClusterChars == 0 {
		cfg.Compaction.L5MaxClusterChars = def.Compaction.L5MaxClusterChars
	}
	if cfg.Compaction.L4ClusterSize == 0 {
		cfg.Compaction.L4ClusterSize = def.Compaction.L4ClusterSize
	}
	if cfg.Compaction.L3EpisodesMin == 0 {
		cfg.Compaction.L3EpisodesMin = def.Compaction.L3EpisodesMin
	}
	if cfg.Compaction.L3ImportanceMin == 0 {
		cfg.Compaction.L3ImportanceMin = def.Compaction.L3ImportanceMin
	}
	if cfg.Compaction.SeedMinL2 == 0 {
		cfg.Compaction.SeedMinL2 = def.Compaction.SeedMinL2
	}
	if cfg.Compaction.SeedMinL3 == 0 {
		cfg.Compaction.SeedMinL3 = def.Compaction.SeedMinL3
	}
	if cfg.Compaction.SeedSample == 0 {
		cfg.Compaction.SeedSample = def.Compaction.SeedSample
	}
	if cfg.Compaction.ValenceCompactionMin == 0 {
		cfg.Compaction.ValenceCompactionMin = def.Compaction.ValenceCompactionMin
	}
}

func applySearchDefaults(cfg, def *Config) {
	if cfg.Search.DefaultTopK == 0 {
		cfg.Search.DefaultTopK = def.Search.DefaultTopK
	}
	if cfg.Search.Alpha == 0 {
		cfg.Search.Alpha = def.Search.Alpha
	}
	if cfg.Search.Beta == 0 {
		cfg.Search.Beta = def.Search.Beta
	}
	if cfg.Search.Gamma == 0 {
		cfg.Search.Gamma = def.Search.Gamma
	}
}
