// NOTE: Any changes to this file must be reflected in the corresponding SPECS.md or NOTES.md.

package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// Load reads a TOML configuration file from path and merges it over the defaults.
// It returns an error if the file does not exist or contains invalid TOML.
// Any fields absent from the file receive their default values.
func Load(path string) (*Config, error) {
	cfg := Default()

	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open config: %w", err)
	}
	defer f.Close() //nolint:errcheck

	if _, err := toml.NewDecoder(f).Decode(cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	// Re-apply defaults for any zero-value fields that were not in the TOML.
	applyDefaults(cfg)

	return cfg, nil
}

// Default returns a Config with all fields set to their default values.
// It resolves the home directory for path defaults; it never writes to the filesystem.
func Default() *Config {
	home, _ := os.UserHomeDir()
	lthDir := filepath.Join(home, ".lth")

	cfg := &Config{}
	cfg.DB.Path = filepath.Join(lthDir, "memory.db")
	cfg.Embedding.Provider = "huggingface"
	cfg.Embedding.AutoDocker = true
	cfg.Embedding.DockerImage = "ghcr.io/huggingface/text-embeddings-inference:cpu-1.5"
	cfg.Embedding.DockerPort = 8080
	cfg.Embedding.BaseURL = "http://localhost:8080"
	cfg.Embedding.Model = "nomic-ai/nomic-embed-text-v1.5"
	cfg.Embedding.TimeoutS = 30
	cfg.LLM.Provider = "anthropic"
	cfg.LLM.BaseURL = "http://localhost:11434"
	cfg.LLM.Model = "claude-haiku-4-5-20251001"
	cfg.LLM.TimeoutS = 60
	cfg.Compaction.IntervalS = 3600
	cfg.Compaction.L5Threshold = 50
	cfg.Compaction.L5MaxAgeH = 24
	cfg.Compaction.L5ClusterThreshold = 0.75
	cfg.Compaction.L5MinClusterSize = 2
	cfg.Compaction.L4ClusterSize = 5
	cfg.Compaction.L3EpisodesMin = 10
	cfg.Compaction.L3ImportanceMin = 7.0
	cfg.Search.DefaultTopK = 10
	cfg.Search.Alpha = 0.333
	cfg.Search.Beta = 0.333
	cfg.Search.Gamma = 0.333
	cfg.Watcher.Paths = []string{filepath.Join(home, ".claude", "projects")}
	cfg.Watcher.StateFile = filepath.Join(lthDir, "watcher-state.json")

	return cfg
}

// ConfigPath returns the canonical path for the lth configuration file.
func ConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("get home dir: %w", err)
	}
	return filepath.Join(home, ".lth", "config.toml"), nil
}

// InitDefault writes the default configuration to path with explanatory comments.
// It returns an error if the file already exists (use force to overwrite).
func InitDefault(path string, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("config file already exists at %s (use --force to overwrite)", path)
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	content := `# lth configuration
# Generated by lth config init

[db]
# Path to the SQLite database file.
# path = "~/.lth/memory.db"

[embedding]
# OpenAI-compatible embeddings endpoint.
base_url = "http://localhost:11434"
model = "nomic-embed-text"
timeout_s = 30

[llm]
# OpenAI-compatible chat completions endpoint.
base_url = "http://localhost:11434"
model = "llama3.2"
timeout_s = 60

[compaction]
interval_s = 3600
l5_threshold = 50
l5_max_age_h = 24
l4_cluster_size = 5
l3_episodes_min = 10
l3_importance_min = 7.0

[search]
default_top_k = 10
alpha = 0.333
beta = 0.333
gamma = 0.333

[watcher]
# paths = ["~/.claude/projects"]
`

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	return nil
}

// applyDefaults fills in any zero-value fields with their defaults.
// This handles partial TOML files where some sections are absent.
func applyDefaults(cfg *Config) {
	def := Default()

	if cfg.DB.Path == "" {
		cfg.DB.Path = def.DB.Path
	}
	if cfg.Embedding.Provider == "" {
		cfg.Embedding.Provider = def.Embedding.Provider
	}
	if cfg.Embedding.DockerImage == "" {
		cfg.Embedding.DockerImage = def.Embedding.DockerImage
	}
	if cfg.Embedding.DockerPort == 0 {
		cfg.Embedding.DockerPort = def.Embedding.DockerPort
	}
	if cfg.Embedding.BaseURL == "" {
		if cfg.Embedding.Provider == "huggingface" {
			cfg.Embedding.BaseURL = "http://localhost:8080"
		} else {
			cfg.Embedding.BaseURL = "http://localhost:11434"
		}
	}
	if cfg.Embedding.Model == "" {
		if cfg.Embedding.Provider == "huggingface" {
			cfg.Embedding.Model = "nomic-ai/nomic-embed-text-v1.5"
		} else {
			cfg.Embedding.Model = def.Embedding.Model
		}
	}
	if cfg.Embedding.TimeoutS == 0 {
		cfg.Embedding.TimeoutS = def.Embedding.TimeoutS
	}
	if cfg.LLM.Provider == "" {
		cfg.LLM.Provider = def.LLM.Provider
	}
	if cfg.LLM.Model == "" {
		switch cfg.LLM.Provider {
		case "anthropic":
			cfg.LLM.Model = "claude-haiku-4-5-20251001"
		default:
			cfg.LLM.Model = "llama3.2"
		}
	}
	if cfg.LLM.BaseURL == "" {
		cfg.LLM.BaseURL = def.LLM.BaseURL
	}
	if cfg.LLM.TimeoutS == 0 {
		cfg.LLM.TimeoutS = def.LLM.TimeoutS
	}
	if cfg.Compaction.IntervalS == 0 {
		cfg.Compaction.IntervalS = def.Compaction.IntervalS
	}
	if cfg.Compaction.L5Threshold == 0 {
		cfg.Compaction.L5Threshold = def.Compaction.L5Threshold
	}
	if cfg.Compaction.L5MaxAgeH == 0 {
		cfg.Compaction.L5MaxAgeH = def.Compaction.L5MaxAgeH
	}
	if cfg.Compaction.L5ClusterThreshold == 0 {
		cfg.Compaction.L5ClusterThreshold = def.Compaction.L5ClusterThreshold
	}
	if cfg.Compaction.L5MinClusterSize == 0 {
		cfg.Compaction.L5MinClusterSize = def.Compaction.L5MinClusterSize
	}
	if cfg.Compaction.L4ClusterSize == 0 {
		cfg.Compaction.L4ClusterSize = def.Compaction.L4ClusterSize
	}
	if cfg.Compaction.L3EpisodesMin == 0 {
		cfg.Compaction.L3EpisodesMin = def.Compaction.L3EpisodesMin
	}
	if cfg.Compaction.L3ImportanceMin == 0 {
		cfg.Compaction.L3ImportanceMin = def.Compaction.L3ImportanceMin
	}
	if cfg.Search.DefaultTopK == 0 {
		cfg.Search.DefaultTopK = def.Search.DefaultTopK
	}
	if cfg.Search.Alpha == 0 {
		cfg.Search.Alpha = def.Search.Alpha
	}
	if cfg.Search.Beta == 0 {
		cfg.Search.Beta = def.Search.Beta
	}
	if cfg.Search.Gamma == 0 {
		cfg.Search.Gamma = def.Search.Gamma
	}
	if len(cfg.Watcher.Paths) == 0 {
		cfg.Watcher.Paths = def.Watcher.Paths
	}
	if cfg.Watcher.StateFile == "" {
		cfg.Watcher.StateFile = def.Watcher.StateFile
	}
}
